name: Get PRs Included

on:
  pull_request:

jobs:
  get_prs:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: 'Bump CommonCpp from `(.......)` to `(.......)`'
          
      - name: Get PRsSinceCommit File
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O https://raw.githubusercontent.com/TechSmith/prs-merged-since-commit/main/prsSinceCommit.ps1
          
      - name: Debugging Stuff
        run: |
            echo "${{ github.event.pull_request.title }}"
            echo "Match is ${{ steps.regex-match.outputs.match }} with ${{ steps.regex-match.outputs.group1 }}, ${{ steps.regex-match.outputs.group2 }}"
            
      - name: Run PowerShell script
        id: prssincecommit
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "A.J. here.  This is an automated comment. :smiley:" > output.txt
          ./prsSinceCommit.ps1 -RepoName MathPuzzleSolver -CommitHash 939ee2f7871f6311a20b8bc590411d4e8575bd2d >> output.txt

      - name: Comment a pull_request
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: output.txt
          reactions: "laugh, heart, hooray, rocket"
          
permissions:
  contents: read
  pull-requests: write
