name: Get PRs Included

on:
  pull_request:
    types: [opened, reopened]

jobs:
  get_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: 'Bump CommonCpp from `(.......)` to `(.......)`'
          
      - name: Get PRsSinceCommit File
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          curl -H "Authorization: token ${{ secrets.GHTOKEN }}" -O https://raw.githubusercontent.com/TechSmith/prs-merged-since-commit/main/prsSinceCommit.ps1

      - name: Run PowerShell script
        id: prssincecommit
        if: ${{ steps.regex-match.outputs.match != '' }}
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "A.J. here.  This is an automated comment. :smiley:" > output.txt
          ./prsSinceCommit.ps1 -RepoName CommonCpp -CommitHash ${{ steps.regex-match.outputs.group1 }} -EndCommitHash ${{ steps.regex-match.outputs.group2 }} >> output.txt

      - name: Comment a pull_request
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: output.txt
          reactions: "laugh, heart, hooray, rocket"

permissions:
  contents: read
  pull-requests: write
