name: Get PRs Included

on:
  pull_request:

jobs:
  get_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: 'Bump CommonCpp from `(.......)` to `(.......)`'
          
      - name: Debugging Stuff
        run: |
            echo "${{ github.event.pull_request.title }}"
            echo "Match is ${{ steps.regex-match.outputs.match }}"
            
      - name: Run PowerShell script
        id: prssincecommit
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $prsoutput =./prsSinceCommit.ps1 -RepoName MathPuzzleSolver -CommitHash 939ee2f7871f6311a20b8bc590411d4e8575bd2d
          echo "PRS_OUTPUT=$prsoutput" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Comment a pull_request
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
             "${{ steps.prssincecommit.outputs.PRS_OUTPUT }} as well as ${{ steps.regex-match.outputs.group1 }}, ${{ steps.regex-match.outputs.group2 }}"
          reactions: "+1, -1, laugh, confused, heart, hooray, rocket, eyes"
          
permissions:
  contents: read
  pull-requests: write
