name: Get PRs Included

on:
  pull_request:

jobs:
  get_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.title }}
          regex: 'Bump CommonCpp from `(.......)` to `(.......)`'

      - name: Comment a pull_request
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
             "Hello, Thank you for this PR!"
          reactions: "+1, -1, laugh, confused, heart, hooray, rocket, eyes"
          
permissions:
  contents: read
  pull-requests: write
