name: Get PRs Included

on:
  pull_request:

jobs:
  get_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.title }}
          regex: 'Bump CommonCpp from `(.......)` to `(.......)`'

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Hello, Thank you for this PR!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
permissions:
  contents: read
  pull-requests: write
