name: Get PRs Included

on:
  pull_request:
    types: [opened, reopened]

jobs:
  get_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: "Bump CommonCpp from `74bc9b4` to `ff001b1`"
          regex: 'Bump CommonCpp from `(.......)` to `(.......)`'
      
      - name: Check out repo with script
        uses: actions/checkout@master
        with:
          repository: TechSmith/prs-merged-since-commit
          token: ${{ secrets.GHTOKEN }}

      - name: Run PowerShell script
        id: prssincecommit
        if: ${{ steps.regex-match.outputs.match != '' }}
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GHTOKEN }}
        run: |
          echo "A.J. here.  This is an automated comment. :smiley:" > output.txt
          ./prs-merged-since-commit/prsSinceCommit.ps1 -RepoName "CommonCpp" -CommitHash "${{ steps.regex-match.outputs.group1 }}" -EndCommitHash "${{ steps.regex-match.outputs.group2 }}" >> output.txt

      - name: Comment a pull_request
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: output.txt
          reactions: "laugh, heart, hooray, rocket"

permissions:
  contents: read
  pull-requests: write
